from datetime import datetime
from uuid import UUID

from pydantic import Field, IPvAnyAddress

from app.models.asset import AssetStatus
from app.schemas.common import RequestModel, ResponseModel


class HostInfo(RequestModel):
    hostname: str = Field(min_length=1, max_length=255)
    os_name: str = Field(min_length=1, max_length=64, examples=["Windows"])
    os_version: str = Field(min_length=1, max_length=128, examples=["11 Pro 24H2"])
    architecture: str = Field(min_length=1, max_length=32, examples=["x86_64"])
    primary_ip: IPvAnyAddress
    agent_version: str = Field(min_length=1, max_length=64, examples=["0.1.0"])
    # Cómo se instaló el agente ("windows_service" desde la Fase 4F). Opcional: los agentes
    # anteriores y los ejecutados a mano no lo envían. Patrón abierto en lugar de una lista
    # cerrada para que un agente más nuevo con otro método no sea rechazado entero (422).
    installation_method: str | None = Field(
        default=None, pattern=r"^[a-z][a-z0-9_]{0,31}$", examples=["windows_service"]
    )
    # Fase 5C.1: identidad estable de la máquina, ya derivada en el agente (HMAC-SHA256 en
    # hexadecimal de /etc/machine-id o MachineGuid). Nunca el valor en claro. Opcional: los
    # agentes anteriores no la envían.
    machine_id_hash: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")


class AgentRegisterRequest(HostInfo):
    agent_id: UUID = Field(description="Stable identifier generated by the agent on first run.")


class AgentRegisterResponse(ResponseModel):
    asset_id: UUID
    agent_id: UUID
    status: AssetStatus
    first_seen_at: datetime
    # Returned only here, once. The server keeps just a hash, so it cannot be shown again.
    agent_token: str


class HeartbeatRequest(RequestModel):
    agent_id: UUID
    # Optional so older agents keep working. When present, the asset's inventory is refreshed
    # (IP changes with DHCP/VPN, OS and agent versions change with updates).
    host: HostInfo | None = None


class HeartbeatResponse(ResponseModel):
    asset_id: UUID
    status: AssetStatus
    last_seen_at: datetime
