import { useCallback } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { ApiError } from "../api/client";
import { sentraApi } from "../api/sentra";
import { AlertsView } from "../components/AlertsView";
import { ChangesList } from "../components/asset/ChangesList";
import { EventsTab } from "../components/asset/EventsTab";
import { NetworkTab } from "../components/asset/NetworkTab";
import { OverviewTab } from "../components/asset/OverviewTab";
import { ProcessesTab } from "../components/asset/ProcessesTab";
import { ServicesTab } from "../components/asset/ServicesTab";
import { SoftwareTab } from "../components/asset/SoftwareTab";
import { UsersTab } from "../components/asset/UsersTab";
import { EmptyState, ErrorState, LoadingState } from "../components/StateViews";
import { StatusBadge } from "../components/StatusBadge";
import { config } from "../config";
import { errorMessage, formatDateTime, formatRelative } from "../lib/format";
import { usePolling } from "../lib/usePolling";

const TABS = [
  { key: "overview", label: "Overview" },
  { key: "processes", label: "Processes" },
  { key: "services", label: "Services" },
  { key: "software", label: "Software" },
  { key: "network", label: "Network" },
  { key: "users", label: "Users" },
  { key: "events", label: "Events" },
  { key: "alerts", label: "Alerts" },
] as const;

type Tab = (typeof TABS)[number]["key"];

// Tabs fed by the inventory snapshot (sent every 15 min): polled only while one is visible.
const INVENTORY_TABS: Tab[] = ["processes", "services", "software", "network", "users"];
const INVENTORY_REFRESH_MS = Math.max(config.refreshIntervalMs, 60_000);

const backLink = (
  <Link to="/" className="back">
    ← Activos
  </Link>
);

function isTab(value: string | null): value is Tab {
  return TABS.some((tab) => tab.key === value);
}

export function AssetDetailPage() {
  const { assetId = "" } = useParams();
  const [params, setParams] = useSearchParams();
  const raw = params.get("tab");
  const tab: Tab = isTab(raw) ? raw : "overview";

  const fetchAsset = useCallback(
    (signal: AbortSignal) => sentraApi.getAsset(assetId, signal),
    [assetId],
  );
  const { data: asset, error, loading, refresh } = usePolling(fetchAsset, config.refreshIntervalMs);
  // 404, or 422 when the id in the URL is not a valid UUID. Such an asset does not appear later
  // (ids are generated by the server), so nothing else is fetched for it.
  const notFound =
    !asset && error instanceof ApiError && (error.status === 404 || error.status === 422);

  const fetchInventory = useCallback(
    (signal: AbortSignal) => sentraApi.getInventory(assetId, signal),
    [assetId],
  );
  const inventory = usePolling(
    fetchInventory,
    INVENTORY_REFRESH_MS,
    !notFound && INVENTORY_TABS.includes(tab),
  );
  const noInventory = inventory.error instanceof ApiError && inventory.error.status === 404;

  if (loading) return <LoadingState label="Cargando activo…" />;

  if (!asset) {
    return (
      <div className="page">
        {backLink}
        {notFound || !error ? (
          <EmptyState title="Activo no encontrado">
            El identificador no corresponde a ningún activo registrado.
          </EmptyState>
        ) : (
          <ErrorState message={errorMessage(error)} onRetry={refresh} />
        )}
      </div>
    );
  }

  const selectTab = (key: Tab) =>
    setParams(key === "overview" ? {} : { tab: key }, { replace: true });
  const inv = inventory.data;

  const inventoryContent = () => {
    if (tab === "processes") {
      // Has its own snapshot endpoint; the inventory list is only a fallback for older agents.
      return <ProcessesTab assetId={asset.asset_id} inventoryProcesses={inv?.processes} />;
    }
    if (inventory.loading) return <LoadingState label="Cargando inventario…" />;
    if (!inv && noInventory) {
      return (
        <EmptyState title="Sin inventario">
          El agente envía el inventario al arrancar y cada 15 minutos.
        </EmptyState>
      );
    }
    if (!inv) {
      return (
        <ErrorState
          message={inventory.error ? errorMessage(inventory.error) : "Sin datos"}
          onRetry={inventory.refresh}
        />
      );
    }
    const collected = (
      <p className="muted small inventory-age" title={formatDateTime(inv.collected_at)}>
        Inventario recogido {formatRelative(inv.collected_at)}
      </p>
    );
    switch (tab) {
      case "services":
        return (
          <div className="stack">
            <section className="panel">
              <ServicesTab services={inv.services} />
            </section>
            {collected}
            <ChangesList assetId={asset.asset_id} category="service" title="Cambios en servicios" />
          </div>
        );
      case "software":
        return (
          <div className="stack">
            <section className="panel">
              <SoftwareTab software={inv.software} />
            </section>
            {collected}
            <ChangesList assetId={asset.asset_id} category="software" title="Cambios de software" />
          </div>
        );
      case "network":
        return (
          <div className="stack">
            <NetworkTab
              interfaces={inv.interfaces}
              connections={inv.connections ?? []}
              summary={inv.network}
            />
            {collected}
          </div>
        );
      case "users":
        return (
          <div className="stack">
            <UsersTab sessions={inv.users} accounts={inv.accounts} />
            {collected}
            <ChangesList assetId={asset.asset_id} category="account" title="Cambios en cuentas" />
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className="page">
      {backLink}
      <div className="page__header">
        <div>
          <h1 className="detail__title">
            {asset.hostname} <StatusBadge status={asset.status} />
          </h1>
          <p className="muted small mono">{asset.asset_id}</p>
        </div>
      </div>

      {error && (
        <div className="banner banner--warn" role="alert">
          Fallo al actualizar: {errorMessage(error)}. Se muestran los últimos datos recibidos.
        </div>
      )}

      <nav className="tabs" role="tablist" aria-label="Secciones del activo">
        {TABS.map(({ key, label }) => (
          <button
            key={key}
            type="button"
            role="tab"
            aria-selected={tab === key}
            className={`tabs__item${tab === key ? " tabs__item--active" : ""}`}
            onClick={() => selectTab(key)}
          >
            {label}
          </button>
        ))}
      </nav>

      <div role="tabpanel">
        {tab === "overview" && <OverviewTab asset={asset} />}
        {INVENTORY_TABS.includes(tab) && inventoryContent()}
        {tab === "events" && <EventsTab assetId={asset.asset_id} />}
        {tab === "alerts" && <AlertsView assetId={asset.asset_id} />}
      </div>
    </div>
  );
}
